ns= set()
n1= int(input("Enter 1st number - "))
n2= int(input("Enter 2nd number - "))
n3= int(input("Enter 3rd number - "))
n4= int(input("Enter 4th number - "))
n5= int(input("Enter 5th number - "))
n6= int(input("Enter 6th number - "))
n7= int(input("Enter 7th number - "))
n8= int(input("Enter 8th number - "))
ns.add(n1)
ns.add(n2)
ns.add(n3)
ns.add(n4)
ns.add(n5)
ns.add(n6)
ns.add(n7)
ns.add(n8)

print(ns)