a = int(input("Enter First value : "))
b = int(input("Enter Second value : "))
c = int(input("Enter Third value : "))
d = int(input("Enter Forth value : "))
e = int(input("Enter Fifth value : "))
f = int(input("Enter Sixth value : "))
g = int(input("Enter Seventh value : "))
h = int(input("Enter Eight value : "))
average = ((a+b+c+d+e+f+g+h)/8)
print("The average is",average)